// Notebook markdown syntax reference — shared by the Settings window's
// Notebook page and (historically) the in-notebook settings panel.
export const SYNTAX_SUBTABS = [
  { id: 'formatting', label: 'Formatting', sections: ['Inline Formatting', 'Inline Styling', 'Headings', 'Auto-wrap Pairs'] },
  { id: 'blocks',     label: 'Blocks',     sections: ['Blocks', 'Inline Math'] },
  { id: 'links',      label: 'Links & Tags', sections: ['Wikilinks', 'Tags & Dates'] },
  { id: 'shortcuts',  label: 'Shortcuts',  sections: ['Shortcuts'] },
]

export const SYNTAX_SECTIONS = [
  { title:'Inline Formatting', rows:[
    {k:'**bold**',d:'Bold'},{k:'*italic*',d:'Italic'},
    {k:'***bold italic***',d:'Bold + italic'},{k:'~~strike~~',d:'Strikethrough'},
    {k:'==highlight==',d:'Highlight'},{k:'`code`',d:'Inline code'},
    {k:'^sup^',d:'Superscript'},{k:'~sub~',d:'Subscript'},
    {k:'[text](url)',d:'Hyperlink'},{k:'![alt](url)',d:'Image'},{k:'![alt :left](url)',d:'Image aligned left/right/center'},
  ]},
  { title:'Inline Styling', rows:[
    {k:'/bold',d:'Bold — wraps following text in bold'},
    {k:'/italic',d:'Italic — wraps following text in italic'},
    {k:'/bi',d:'Bold italic — wraps following text in bold + italic'},
    {k:'/strike',d:'Strikethrough — wraps following text'},
    {k:'/highlight',d:'Highlight — wraps following text with a yellow background'},
    {k:'/code',d:'Inline code — monospace font + background'},
    {k:'/sup',d:'Superscript — smaller text raised above baseline'},
    {k:'/sub',d:'Subscript — smaller text lowered below baseline'},
    {k:'/color:red',d:'Text color — any CSS color (name, hex, rgb, var)'},
    {k:'/font:Georgia',d:'Font family — any CSS font name'},
    {k:'/size:1.2em',d:'Font size — any CSS size (em, px, %)'},
    {k:'/spacing:2',d:'Line height — any CSS line-height value'},
    {k:'/align:center',d:'Align text — left, center, right, justify (applies per line)'},
    {k:'/columns:2',d:'Multi-column layout — 1–4 columns (applies per line)'},
    {k:'{//}',d:'Close — stops the inline style at this point; type // to auto-insert'},
  ]},
  { title:'Headings', rows:[
    {k:'# H1',d:'Heading 1'},{k:'## H2',d:'Heading 2'},{k:'### H3',d:'Heading 3'},
    {k:'#### H4',d:'H4'},{k:'##### H5',d:'H5'},{k:'###### H6',d:'H6'},
  ]},
  { title:'Blocks', rows:[
    {k:'> text',d:'Blockquote'},{k:'> [!NOTE]',d:'Callout'},
    {k:'- item',d:'Unordered list'},{k:'1. item',d:'Ordered list'},
    {k:'  - nested',d:'Nested list (2 spaces)'},{k:'- [ ] task',d:'Task item'},
    {k:'- [x] done',d:'Checked task (clickable)'},{k:'```lang',d:'Code block'},
    {k:'---',d:'Horizontal rule'},{k:'| a | b |',d:'Table'},
    {k:'/habits',d:'Habit tracker (add habits, check off per day)'},
    {k:'/task or /task:Title',d:'Kanban board'},
    {k:'/timer mm:ss or hh:mm:ss',d:'Countdown timer with progress bar'},
    {k:'/math … /math end',d:'Calculator zone — "price: 4" variables and "2+2=" ghost results only work here'},
    {k:'/calendar',d:'Interactive inline calendar'},
    {k:'?[question]()',d:'Review question — click to set date or link to flashcard deck'},
    {k:'[^1]: note',d:'Footnote definition'},
    {k:'$math$',d:'Inline math (MathQuill — click to edit)'},
    {k:'$$\nmath\n$$',d:'Math block (MathQuill — click to edit)'},
  ]},
  { title:'Wikilinks', rows:[
    {k:'[[Title]]',d:'Link to note or book'},
    {k:'Type [[',d:'Dropdown — up to 4 suggestions'},
    {k:'Click link',d:'Opens; creates missing notes'},
  ]},
  { title:'Tags & Dates', rows:[
    {k:'::meeting',d:'Tag — renders as a #meeting badge; searchable in library'},
    {k:'::important',d:'Another tag example — use any word after ::'},
    {k:'::2026-03-18',d:'Due date (year-month-day)'},
    {k:'::18-03-2026',d:'Due date (day-month-year)'},
    {k:'::18-03-26',d:'Due date (day-month-2-digit year)'},
    {k:'::18-03-2026,14:30',d:'Due date + time (2:30 PM = 14:30)'},
    {k:'::14:30',d:'Due today at 14:30'},
    {k:'::+2d',d:'Due in 2 days from now'},
    {k:'::+3h',d:'Due in 3 hours from now'},
  ]},
  { title:'Auto-wrap Pairs', rows:[
    {k:'Select text → type **',d:'Wraps selection with **…**'},
    {k:'Select text → type *',d:'Wraps selection with *…*'},
    {k:'Select text → type `',d:'Wraps selection with `…`'},
    {k:'Select text → type ~~',d:'Wraps selection with ~~…~~'},
    {k:'Select text → type ==',d:'Wraps selection with ==…=='},
    {k:'Select text → type $',d:'Wraps selection with $…$'},
  ]},
  { title:'Inline Math', rows:[
    {k:'2+2 =',d:'Shows answer as ghost hint — press Tab to accept'},
    {k:'2*32.12321 =:.2',d:'Round result to 2 decimals → 64.25'},
    {k:'5 km to miles =',d:'Unit conversion via math.js'},
    {k:'@14:30',d:'Time reference (24h format)'},
    {k:'@2:30pm',d:'Time reference (12h format)'},
  ]},
  { title:'Shortcuts', rows:[
    {k:'Ctrl+B',d:'Bold'},{k:'Ctrl+I',d:'Italic'},{k:'Ctrl+K',d:'Link'},
    {k:'Ctrl+E',d:'Code'},{k:'Ctrl+Shift+H',d:'Highlight'},
    {k:'Ctrl+S',d:'Save'},{k:'Ctrl+F',d:'Find'},
    {k:'Tab',d:'Indent list'},{k:'Enter',d:'Smart list continue'},
  ]},
]
