// Vendor the webfonts into public/fonts/ so the app doesn't need a network.
//
// index.html used to <link> straight to api.fontshare.com and
// fonts.googleapis.com. In a packaged desktop app that means every launch
// without a network falls back to system fonts — the whole typographic
// identity, including the reader, silently changes.
//
// This is a ONE-TIME vendoring step, not a build step: the output is committed.
// Re-run it only to add a family or refresh versions:
//     node scripts/vendor-fonts.mjs
//
// It fetches each provider stylesheet with a modern desktop UA (so they serve
// woff2 rather than legacy formats), downloads every referenced font binary,
// and rewrites the @font-face src URLs to local relative paths.

import { mkdir, writeFile, rm } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = join(root, 'public', 'fonts')

// Chrome UA — Google/Fontshare content-negotiate on this and serve woff2 only
// to browsers they recognise. With a default fetch UA you get bloated formats.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

const SHEETS = [
  {
    name: 'fontshare',
    url: 'https://api.fontshare.com/v2/css?f[]=clash-display@400,500,600,700&f[]=satoshi@300,400,500,600,700,800,900&f[]=switzer@400,500,600,700&f[]=erode@400,500,600,700&f[]=britney@400,600&display=swap',
  },
  {
    name: 'google',
    url: 'https://fonts.googleapis.com/css2?family=Stack+Sans+Text:wght@400;500;600;700&family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,600&family=Inter:wght@400;500;600&display=swap',
  },
]

async function get(url, as = 'text') {
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`)
  return as === 'text' ? res.text() : Buffer.from(await res.arrayBuffer())
}

await rm(outDir, { recursive: true, force: true })
await mkdir(outDir, { recursive: true })

let combined = '/* Generated by scripts/vendor-fonts.mjs — do not edit by hand. */\n'
let fileCount = 0
let byteCount = 0

for (const sheet of SHEETS) {
  let css = await get(sheet.url)
  const urls = [...new Set([...css.matchAll(/url\((https:\/\/[^)]+)\)/g)].map(m => m[1]))]

  for (const fontUrl of urls) {
    // Stable, collision-proof local name: provider + last two path segments.
    const parts = new URL(fontUrl).pathname.split('/').filter(Boolean)
    const local = `${sheet.name}-${parts.slice(-2).join('-')}`.replace(/[^\w.-]/g, '_')
    const bytes = await get(fontUrl, 'bin')
    await writeFile(join(outDir, local), bytes)
    css = css.split(fontUrl).join(`./${local}`)
    fileCount++
    byteCount += bytes.length
    process.stdout.write(`\r[fonts] ${fileCount} files, ${(byteCount / 1e6).toFixed(1)}MB`)
  }
  combined += `\n/* ── ${sheet.name} ─────────────────────────────────── */\n${css}\n`
}

await writeFile(join(outDir, 'fonts.css'), combined)
console.log(`\n[fonts] wrote public/fonts/fonts.css + ${fileCount} font files (${(byteCount / 1e6).toFixed(1)}MB)`)
